experimentName: SVMclassifier
searchSpaceFile: SVM_search_space.json
trialCommand: python SVM_trial.py
trialCodeDirectory: .
trialConcurrency: 8
maxExperimentDuration: 48h
maxTrialNumber: 99999
tuner:
  # choice:
  # TPE, Anneal, Evolution, SMAC, BatchTuner, GridSearch, Hyperband
  # NetworkMorphism, MetisTuner, BOHB, GPTuner, PBTTuner, DNGOTuner
  # SMAC need to be installed (pip install nni[SMAC])
  # https://nni.readthedocs.io/en/stable/Tuner/BuiltinTuner.html#Evolution
  name: Anneal
  classArgs:
    optimize_mode: minimize # maximize or minimize
trainingService:
  platform: local
  useActiveGpu: True